import { channel } from '@/channel.config';
import type { Locale } from '@/i18n';

type ChannelCopy = {
  name: string;
  tagline: string;
  description: string;
  keywords: string[];
};

const CHANNEL_COPIES: Record<string, Record<Locale, ChannelCopy>> = {
  MACRO: {
    ko: { name: '매크로시그널', tagline: '금리·연준·인플레이션 신호를 매일 빠르게', description: 'Fed·한국은행·ECB의 금리 결정, CPI, GDP, 고용지표 등 거시경제 신호를 초등생도 이해할 수 있게 풀어드립니다.', keywords: ['거시경제', '금리', '연준', '인플레이션', 'CPI', 'GDP'] },
    en: { name: 'Macro Signal', tagline: 'Daily signals on rates, the Fed, and inflation', description: 'Plain-language coverage of central banks, inflation, GDP, jobs data, and macro market signals.', keywords: ['macro economy', 'rates', 'Federal Reserve', 'inflation', 'CPI', 'GDP'] },
    ja: { name: 'マクロシグナル', tagline: '金利・FRB・インフレのシグナルを毎日素早く', description: '中央銀行、インフレ、GDP、雇用統計などのマクロ経済ニュースをわかりやすく解説します。', keywords: ['マクロ経済', '金利', 'FRB', 'インフレ', 'CPI', 'GDP'] },
    zh: { name: '宏观信号', tagline: '每日追踪利率、美联储与通胀信号', description: '用清晰语言解读央行政策、通胀、GDP、就业数据与宏观市场信号。', keywords: ['宏观经济', '利率', '美联储', '通胀', 'CPI', 'GDP'] },
    es: { name: 'Macro Signal', tagline: 'Señales diarias sobre tasas, la Fed e inflación', description: 'Explicamos bancos centrales, inflación, PIB, empleo y señales macro de mercado en lenguaje claro.', keywords: ['macroeconomía', 'tasas', 'Reserva Federal', 'inflación', 'IPC', 'PIB'] },
    pt: { name: 'Sinal Macro', tagline: 'Sinais diários sobre juros, Fed e inflação', description: 'Cobertura simples de bancos centrais, inflação, PIB, emprego e sinais macro dos mercados.', keywords: ['macroeconomia', 'juros', 'Federal Reserve', 'inflação', 'IPC', 'PIB'] },
    de: { name: 'Makro-Signal', tagline: 'Tägliche Signale zu Zinsen, Fed und Inflation', description: 'Verständliche Einordnung von Zentralbanken, Inflation, BIP, Arbeitsmarkt und Makrosignalen.', keywords: ['Makroökonomie', 'Zinsen', 'Federal Reserve', 'Inflation', 'VPI', 'BIP'] },
    fr: { name: 'Signal Macro', tagline: 'Signaux quotidiens sur les taux, la Fed et l’inflation', description: 'Une lecture claire des banques centrales, de l’inflation, du PIB, de l’emploi et des signaux macro.', keywords: ['macroéconomie', 'taux', 'Réserve fédérale', 'inflation', 'IPC', 'PIB'] },
    ar: { name: 'إشارة الاقتصاد الكلي', tagline: 'إشارات يومية عن الفائدة والفيدرالي والتضخم', description: 'شرح مبسط لقرارات البنوك المركزية والتضخم والناتج المحلي والوظائف وإشارات الاقتصاد الكلي.', keywords: ['اقتصاد كلي', 'الفائدة', 'الاحتياطي الفيدرالي', 'التضخم', 'مؤشر الأسعار', 'الناتج المحلي'] },
    hi: { name: 'मैक्रो सिग्नल', tagline: 'दरें, फेड और महंगाई के दैनिक संकेत', description: 'केंद्रीय बैंक, महंगाई, GDP, रोजगार और मैक्रो बाजार संकेतों को आसान भाषा में समझाया जाता है।', keywords: ['मैक्रो अर्थव्यवस्था', 'ब्याज दरें', 'फेडरल रिजर्व', 'महंगाई', 'CPI', 'GDP'] },
    id: { name: 'Sinyal Makro', tagline: 'Sinyal harian suku bunga, The Fed, dan inflasi', description: 'Ulasan sederhana tentang bank sentral, inflasi, PDB, data tenaga kerja, dan sinyal makro pasar.', keywords: ['makroekonomi', 'suku bunga', 'Federal Reserve', 'inflasi', 'CPI', 'PDB'] }
  },
  ETF: {
    ko: { name: 'ETF와이어', tagline: 'ETF·펀드·패시브 투자, 매일 5분으로', description: '국내외 ETF, 액티브/패시브 펀드, 인덱스 투자, 자금 흐름을 초등생도 이해할 수 있게 정리합니다.', keywords: ['ETF', '펀드', '패시브', '인덱스', '자금흐름', '자산배분'] },
    en: { name: 'ETF Wire', tagline: 'ETF, fund, and passive investing news in five minutes', description: 'Clear coverage of ETFs, active and passive funds, index investing, flows, and asset allocation.', keywords: ['ETF', 'funds', 'passive investing', 'index', 'fund flows', 'asset allocation'] },
    ja: { name: 'ETFワイヤー', tagline: 'ETF・ファンド・パッシブ投資を毎日5分で', description: 'ETF、アクティブ/パッシブファンド、指数投資、資金フローをわかりやすく整理します。', keywords: ['ETF', 'ファンド', 'パッシブ投資', '指数', '資金フロー', '資産配分'] },
    zh: { name: 'ETF快讯', tagline: '每天5分钟看懂ETF、基金与被动投资', description: '清晰整理ETF、主动与被动基金、指数投资、资金流向和资产配置。', keywords: ['ETF', '基金', '被动投资', '指数', '资金流', '资产配置'] },
    es: { name: 'ETF Wire', tagline: 'ETF, fondos e inversión pasiva en cinco minutos', description: 'Cobertura clara de ETF, fondos activos y pasivos, inversión indexada, flujos y asignación de activos.', keywords: ['ETF', 'fondos', 'inversión pasiva', 'índices', 'flujos', 'asignación de activos'] },
    pt: { name: 'ETF Wire', tagline: 'ETFs, fundos e investimento passivo em cinco minutos', description: 'Cobertura clara de ETFs, fundos ativos e passivos, índices, fluxos e alocação de ativos.', keywords: ['ETF', 'fundos', 'investimento passivo', 'índices', 'fluxos', 'alocação de ativos'] },
    de: { name: 'ETF Wire', tagline: 'ETFs, Fonds und passives Investieren in fünf Minuten', description: 'Klare Einordnung von ETFs, aktiven und passiven Fonds, Indexanlagen, Mittelflüssen und Allokation.', keywords: ['ETF', 'Fonds', 'passives Investieren', 'Index', 'Mittelflüsse', 'Asset-Allokation'] },
    fr: { name: 'ETF Wire', tagline: 'ETF, fonds et investissement passif en cinq minutes', description: 'Une lecture claire des ETF, fonds actifs et passifs, indices, flux et allocations d’actifs.', keywords: ['ETF', 'fonds', 'investissement passif', 'indices', 'flux', 'allocation d’actifs'] },
    ar: { name: 'ETF واير', tagline: 'أخبار ETF والصناديق والاستثمار السلبي في خمس دقائق', description: 'تغطية مبسطة لصناديق ETF والصناديق النشطة والسلبية والمؤشرات والتدفقات وتوزيع الأصول.', keywords: ['ETF', 'صناديق', 'استثمار سلبي', 'مؤشرات', 'تدفقات الأموال', 'توزيع الأصول'] },
    hi: { name: 'ETF वायर', tagline: 'ETF, फंड और पैसिव निवेश पांच मिनट में', description: 'ETF, सक्रिय और पैसिव फंड, इंडेक्स निवेश, फंड फ्लो और एसेट एलोकेशन की आसान कवरेज।', keywords: ['ETF', 'फंड', 'पैसिव निवेश', 'इंडेक्स', 'फंड फ्लो', 'एसेट एलोकेशन'] },
    id: { name: 'ETF Wire', tagline: 'ETF, dana, dan investasi pasif dalam lima menit', description: 'Ulasan jelas tentang ETF, dana aktif dan pasif, investasi indeks, arus dana, dan alokasi aset.', keywords: ['ETF', 'dana', 'investasi pasif', 'indeks', 'arus dana', 'alokasi aset'] }
  },
  STOCKS: {
    ko: { name: '글로벌스톡펄스', tagline: '코스피·S&P·나스닥 종목과 시장을 한눈에', description: '한국·미국·일본·중국 주식시장 동향과 종목 분석을 초등생도 이해할 수 있게 풀어드립니다.', keywords: ['주식', '코스피', '나스닥', 'S&P500', '종목분석', '실적'] },
    en: { name: 'Global Stock Pulse', tagline: 'KOSPI, S&P, Nasdaq, and global stocks at a glance', description: 'Plain-language stock market news and analysis across Korea, the U.S., Japan, China, and global equities.', keywords: ['stocks', 'KOSPI', 'Nasdaq', 'S&P 500', 'earnings', 'stock analysis'] },
    ja: { name: 'グローバル株式パルス', tagline: 'KOSPI・S&P・ナスダックと世界株を一目で', description: '韓国、米国、日本、中国、世界株の市場動向と銘柄分析をわかりやすく解説します。', keywords: ['株式', 'KOSPI', 'ナスダック', 'S&P 500', '決算', '銘柄分析'] },
    zh: { name: '全球股票脉搏', tagline: '一站追踪KOSPI、标普、纳斯达克与全球股票', description: '用清晰语言解读韩国、美国、日本、中国及全球股票市场动态和个股分析。', keywords: ['股票', 'KOSPI', '纳斯达克', '标普500', '财报', '个股分析'] },
    es: { name: 'Global Stock Pulse', tagline: 'KOSPI, S&P, Nasdaq y acciones globales de un vistazo', description: 'Noticias y análisis bursátil en lenguaje claro sobre Corea, EE. UU., Japón, China y mercados globales.', keywords: ['acciones', 'KOSPI', 'Nasdaq', 'S&P 500', 'resultados', 'análisis bursátil'] },
    pt: { name: 'Pulso Global de Ações', tagline: 'KOSPI, S&P, Nasdaq e ações globais em um só lugar', description: 'Notícias e análises simples sobre bolsas da Coreia, EUA, Japão, China e ações globais.', keywords: ['ações', 'KOSPI', 'Nasdaq', 'S&P 500', 'resultados', 'análise de ações'] },
    de: { name: 'Global Stock Pulse', tagline: 'KOSPI, S&P, Nasdaq und globale Aktien im Überblick', description: 'Verständliche Aktiennachrichten und Analysen zu Korea, USA, Japan, China und globalen Märkten.', keywords: ['Aktien', 'KOSPI', 'Nasdaq', 'S&P 500', 'Ergebnisse', 'Aktienanalyse'] },
    fr: { name: 'Global Stock Pulse', tagline: 'KOSPI, S&P, Nasdaq et actions mondiales en un coup d’œil', description: 'Actualité et analyse boursière claire sur la Corée, les États-Unis, le Japon, la Chine et les marchés mondiaux.', keywords: ['actions', 'KOSPI', 'Nasdaq', 'S&P 500', 'résultats', 'analyse actions'] },
    ar: { name: 'نبض الأسهم العالمية', tagline: 'نظرة سريعة على كوسبي وS&P وناسداك والأسهم العالمية', description: 'أخبار وتحليلات مبسطة لأسواق الأسهم في كوريا والولايات المتحدة واليابان والصين والعالم.', keywords: ['أسهم', 'كوسبي', 'ناسداك', 'S&P 500', 'أرباح', 'تحليل الأسهم'] },
    hi: { name: 'ग्लोबल स्टॉक पल्स', tagline: 'KOSPI, S&P, Nasdaq और वैश्विक शेयर एक नजर में', description: 'कोरिया, अमेरिका, जापान, चीन और वैश्विक शेयर बाजारों की आसान खबरें और विश्लेषण।', keywords: ['शेयर', 'KOSPI', 'Nasdaq', 'S&P 500', 'आय', 'स्टॉक विश्लेषण'] },
    id: { name: 'Global Stock Pulse', tagline: 'KOSPI, S&P, Nasdaq, dan saham global dalam satu tampilan', description: 'Berita dan analisis pasar saham Korea, AS, Jepang, China, dan global dengan bahasa sederhana.', keywords: ['saham', 'KOSPI', 'Nasdaq', 'S&P 500', 'laba', 'analisis saham'] }
  },
  FX: {
    ko: { name: '외환원자재나우', tagline: '달러·엔·금·원유·곡물 시장 매일 추적', description: '환율, 금, 원유, 천연가스, 농산물 등 외환·원자재 시장을 초등생도 이해할 수 있게 풀어드립니다.', keywords: ['외환', '환율', '달러', '금', '원유', '원자재'] },
    en: { name: 'FX & Commodities Now', tagline: 'Daily tracking of the dollar, yen, gold, oil, and grains', description: 'Clear coverage of currencies, gold, crude oil, natural gas, crops, and commodity market signals.', keywords: ['FX', 'exchange rates', 'dollar', 'gold', 'oil', 'commodities'] },
    ja: { name: '為替コモディティNow', tagline: 'ドル・円・金・原油・穀物市場を毎日追跡', description: '為替、金、原油、天然ガス、農産物などの商品市場をわかりやすく解説します。', keywords: ['為替', 'レート', 'ドル', '金', '原油', '商品'] },
    zh: { name: '外汇大宗商品Now', tagline: '每日追踪美元、日元、黄金、原油与谷物', description: '清晰解读汇率、黄金、原油、天然气、农产品和大宗商品市场信号。', keywords: ['外汇', '汇率', '美元', '黄金', '原油', '大宗商品'] },
    es: { name: 'FX y Materias Primas Now', tagline: 'Seguimiento diario del dólar, yen, oro, petróleo y granos', description: 'Cobertura clara de divisas, oro, crudo, gas natural, cultivos y señales de materias primas.', keywords: ['divisas', 'tipos de cambio', 'dólar', 'oro', 'petróleo', 'materias primas'] },
    pt: { name: 'FX e Commodities Now', tagline: 'Acompanhamento diário de dólar, iene, ouro, petróleo e grãos', description: 'Cobertura clara de câmbio, ouro, petróleo, gás natural, agrícolas e sinais de commodities.', keywords: ['câmbio', 'taxas', 'dólar', 'ouro', 'petróleo', 'commodities'] },
    de: { name: 'FX & Rohstoffe Now', tagline: 'Täglicher Blick auf Dollar, Yen, Gold, Öl und Getreide', description: 'Klare Einordnung von Devisen, Gold, Öl, Erdgas, Agrarrohstoffen und Rohstoffsignalen.', keywords: ['Devisen', 'Wechselkurse', 'Dollar', 'Gold', 'Öl', 'Rohstoffe'] },
    fr: { name: 'FX & Matières Premières Now', tagline: 'Suivi quotidien du dollar, du yen, de l’or, du pétrole et des céréales', description: 'Une lecture claire des changes, de l’or, du pétrole, du gaz naturel, des agricoles et des matières premières.', keywords: ['forex', 'changes', 'dollar', 'or', 'pétrole', 'matières premières'] },
    ar: { name: 'الفوركس والسلع الآن', tagline: 'متابعة يومية للدولار والين والذهب والنفط والحبوب', description: 'تغطية مبسطة للعملات والذهب والنفط والغاز الطبيعي والمحاصيل وإشارات أسواق السلع.', keywords: ['فوركس', 'أسعار الصرف', 'دولار', 'ذهب', 'نفط', 'سلع'] },
    hi: { name: 'FX और कमोडिटीज नाउ', tagline: 'डॉलर, येन, सोना, तेल और अनाज का दैनिक ट्रैक', description: 'मुद्रा, सोना, कच्चा तेल, प्राकृतिक गैस, कृषि जिंस और कमोडिटी संकेतों की आसान कवरेज।', keywords: ['FX', 'विनिमय दर', 'डॉलर', 'सोना', 'तेल', 'कमोडिटी'] },
    id: { name: 'FX & Komoditas Now', tagline: 'Pantauan harian dolar, yen, emas, minyak, dan biji-bijian', description: 'Ulasan jelas tentang valuta, emas, minyak mentah, gas alam, hasil pertanian, dan sinyal komoditas.', keywords: ['FX', 'kurs', 'dolar', 'emas', 'minyak', 'komoditas'] }
  },
  REALESTATE: {
    ko: { name: '코리아부동산데일리', tagline: '한국 부동산 시세 · 정책 · 분양 소식을 매일 5분 안에', description: '아파트 시세, 청약, 정부 부동산 정책, 분양·재건축 뉴스를 초등생도 이해할 수 있게 정리합니다.', keywords: ['부동산', '아파트', '청약', '분양', '시세', '재건축'] },
    en: { name: 'Korea Real Estate Daily', tagline: 'Korean property prices, policy, and presale news in five minutes', description: 'Plain-language coverage of apartments, subscriptions, housing policy, presales, and redevelopment in Korea.', keywords: ['Korea real estate', 'apartments', 'housing policy', 'presales', 'prices', 'redevelopment'] },
    ja: { name: '韓国不動産デイリー', tagline: '韓国不動産の価格・政策・分譲ニュースを5分で', description: '韓国のマンション相場、申込、住宅政策、分譲、再建築ニュースをわかりやすく整理します。', keywords: ['韓国不動産', 'マンション', '住宅政策', '分譲', '価格', '再建築'] },
    zh: { name: '韩国房地产日报', tagline: '5分钟看懂韩国房价、政策与预售新闻', description: '清晰整理韩国公寓价格、认购、住房政策、预售与重建新闻。', keywords: ['韩国房地产', '公寓', '住房政策', '预售', '价格', '重建'] },
    es: { name: 'Korea Real Estate Daily', tagline: 'Precios, política y preventas inmobiliarias de Corea en cinco minutos', description: 'Cobertura clara de apartamentos, suscripciones, política de vivienda, preventas y remodelación en Corea.', keywords: ['inmobiliario Corea', 'apartamentos', 'política de vivienda', 'preventas', 'precios', 'reconstrucción'] },
    pt: { name: 'Korea Real Estate Daily', tagline: 'Preços, política e lançamentos imobiliários da Coreia em cinco minutos', description: 'Cobertura clara de apartamentos, inscrições, política habitacional, lançamentos e reconstrução na Coreia.', keywords: ['imóveis Coreia', 'apartamentos', 'política habitacional', 'lançamentos', 'preços', 'reconstrução'] },
    de: { name: 'Korea Real Estate Daily', tagline: 'Koreas Immobilienpreise, Politik und Vorverkäufe in fünf Minuten', description: 'Verständliche Nachrichten zu Wohnungen, Zeichnungen, Wohnpolitik, Vorverkäufen und Sanierung in Korea.', keywords: ['Korea Immobilien', 'Wohnungen', 'Wohnpolitik', 'Vorverkauf', 'Preise', 'Sanierung'] },
    fr: { name: 'Korea Real Estate Daily', tagline: 'Prix, politique et préventes immobilières coréennes en cinq minutes', description: 'Une lecture claire des appartements, souscriptions, politiques du logement, préventes et rénovations en Corée.', keywords: ['immobilier Corée', 'appartements', 'politique du logement', 'préventes', 'prix', 'reconstruction'] },
    ar: { name: 'العقارات الكورية اليومية', tagline: 'أسعار وسياسات ومبيعات العقار في كوريا خلال خمس دقائق', description: 'تغطية مبسطة للشقق والاشتراكات وسياسات الإسكان والمبيعات المسبقة وإعادة التطوير في كوريا.', keywords: ['عقارات كوريا', 'شقق', 'سياسة الإسكان', 'مبيعات مسبقة', 'أسعار', 'إعادة تطوير'] },
    hi: { name: 'कोरिया रियल एस्टेट डेली', tagline: 'कोरियाई संपत्ति कीमतें, नीति और प्रीसेल खबरें पांच मिनट में', description: 'कोरिया के अपार्टमेंट, आवास नीति, प्रीसेल, कीमतों और पुनर्विकास की आसान कवरेज।', keywords: ['कोरिया रियल एस्टेट', 'अपार्टमेंट', 'आवास नीति', 'प्रीसेल', 'कीमतें', 'पुनर्विकास'] },
    id: { name: 'Korea Real Estate Daily', tagline: 'Harga, kebijakan, dan presale properti Korea dalam lima menit', description: 'Ulasan sederhana tentang apartemen, langganan hunian, kebijakan perumahan, presale, dan redevelopment di Korea.', keywords: ['properti Korea', 'apartemen', 'kebijakan perumahan', 'presale', 'harga', 'redevelopment'] }
  },
  CRYPTO: {
    ko: { name: '크립토데일리', tagline: '비트코인·이더리움·디파이를 매일 쉽게', description: '비트코인, 이더리움, 알트코인, 디파이, NFT, 규제 뉴스를 초등생도 이해할 수 있게 정리합니다.', keywords: ['비트코인', '이더리움', '암호화폐', '코인', '디파이', '블록체인'] },
    en: { name: 'Crypto Daily', tagline: 'Bitcoin, Ethereum, and DeFi explained daily', description: 'Plain-language news on Bitcoin, Ethereum, altcoins, DeFi, NFTs, blockchain, and crypto regulation.', keywords: ['Bitcoin', 'Ethereum', 'crypto', 'altcoins', 'DeFi', 'blockchain'] },
    ja: { name: 'クリプトデイリー', tagline: 'ビットコイン・イーサリアム・DeFiを毎日わかりやすく', description: 'ビットコイン、イーサリアム、アルトコイン、DeFi、NFT、規制ニュースを整理します。', keywords: ['ビットコイン', 'イーサリアム', '暗号資産', 'アルトコイン', 'DeFi', 'ブロックチェーン'] },
    zh: { name: '加密日报', tagline: '每日轻松看懂比特币、以太坊与DeFi', description: '清晰整理比特币、以太坊、山寨币、DeFi、NFT、区块链和加密监管新闻。', keywords: ['比特币', '以太坊', '加密货币', '山寨币', 'DeFi', '区块链'] },
    es: { name: 'Crypto Daily', tagline: 'Bitcoin, Ethereum y DeFi explicados cada día', description: 'Noticias claras sobre Bitcoin, Ethereum, altcoins, DeFi, NFT, blockchain y regulación cripto.', keywords: ['Bitcoin', 'Ethereum', 'cripto', 'altcoins', 'DeFi', 'blockchain'] },
    pt: { name: 'Crypto Daily', tagline: 'Bitcoin, Ethereum e DeFi explicados todos os dias', description: 'Notícias simples sobre Bitcoin, Ethereum, altcoins, DeFi, NFTs, blockchain e regulação cripto.', keywords: ['Bitcoin', 'Ethereum', 'cripto', 'altcoins', 'DeFi', 'blockchain'] },
    de: { name: 'Crypto Daily', tagline: 'Bitcoin, Ethereum und DeFi täglich erklärt', description: 'Klare Nachrichten zu Bitcoin, Ethereum, Altcoins, DeFi, NFTs, Blockchain und Kryptoregulierung.', keywords: ['Bitcoin', 'Ethereum', 'Krypto', 'Altcoins', 'DeFi', 'Blockchain'] },
    fr: { name: 'Crypto Daily', tagline: 'Bitcoin, Ethereum et DeFi expliqués chaque jour', description: 'Actualité claire sur Bitcoin, Ethereum, altcoins, DeFi, NFT, blockchain et régulation crypto.', keywords: ['Bitcoin', 'Ethereum', 'crypto', 'altcoins', 'DeFi', 'blockchain'] },
    ar: { name: 'كريبتو ديلي', tagline: 'شرح يومي لبيتكوين وإيثريوم والتمويل اللامركزي', description: 'أخبار مبسطة عن بيتكوين وإيثريوم والعملات البديلة وDeFi وNFT والبلوكتشين وتنظيم العملات الرقمية.', keywords: ['بيتكوين', 'إيثريوم', 'عملات رقمية', 'عملات بديلة', 'DeFi', 'بلوكتشين'] },
    hi: { name: 'क्रिप्टो डेली', tagline: 'Bitcoin, Ethereum और DeFi की रोज आसान व्याख्या', description: 'Bitcoin, Ethereum, altcoins, DeFi, NFT, blockchain और crypto regulation की सरल खबरें।', keywords: ['Bitcoin', 'Ethereum', 'crypto', 'altcoins', 'DeFi', 'blockchain'] },
    id: { name: 'Crypto Daily', tagline: 'Bitcoin, Ethereum, dan DeFi dijelaskan setiap hari', description: 'Berita sederhana tentang Bitcoin, Ethereum, altcoin, DeFi, NFT, blockchain, dan regulasi kripto.', keywords: ['Bitcoin', 'Ethereum', 'kripto', 'altcoin', 'DeFi', 'blockchain'] }
  }
};

const LABELS: Record<string, Record<Locale, string>> = {
  latestNews: { ko: '최신 뉴스', en: 'Latest News', ja: '最新ニュース', zh: '最新新闻', es: 'Últimas noticias', pt: 'Últimas notícias', de: 'Neueste Nachrichten', fr: 'Dernières nouvelles', ar: 'آخر الأخبار', hi: 'ताज़ा खबरें', id: 'Berita terbaru' },
  mostRead: { ko: '많이 본 뉴스', en: 'Most read', ja: 'よく読まれた記事', zh: '热门阅读', es: 'Más leído', pt: 'Mais lidas', de: 'Meistgelesen', fr: 'Les plus lus', ar: 'الأكثر قراءة', hi: 'सबसे ज्यादा पढ़ा गया', id: 'Paling dibaca' },
  markets: { ko: '시장 지표', en: 'Markets', ja: '市場指標', zh: '市场指标', es: 'Mercados', pt: 'Mercados', de: 'Märkte', fr: 'Marchés', ar: 'الأسواق', hi: 'बाजार', id: 'Pasar' },
  explore: { ko: '둘러보기', en: 'Explore', ja: '探す', zh: '浏览', es: 'Explorar', pt: 'Explorar', de: 'Entdecken', fr: 'Explorer', ar: 'استكشاف', hi: 'देखें', id: 'Jelajahi' },
  readerPaths: { ko: '탐색 경로', en: 'Reader paths', ja: '読者向け導線', zh: '阅读路径', es: 'Rutas de lectura', pt: 'Rotas de leitura', de: 'Lesepfade', fr: 'Parcours de lecture', ar: 'مسارات القراءة', hi: 'पढ़ने के रास्ते', id: 'Jalur baca' },
  searchPriority: { ko: '검색 우선 경로', en: 'Search priority', ja: '検索優先ページ', zh: '搜索优先路径', es: 'Prioridad de búsqueda', pt: 'Prioridade de busca', de: 'Suchpriorität', fr: 'Priorité recherche', ar: 'أولوية البحث', hi: 'सर्च प्राथमिकता', id: 'Prioritas pencarian' },
  searchPriorityBody: { ko: '대표 기사에서 카테고리, 관련 기사, 사이트맵까지 자연스럽게 이어지도록 구성했습니다.', en: 'Start with the lead story, then move through categories, related articles, and sitemap paths.', ja: '主要記事からカテゴリ、関連記事、サイトマップへ自然に進めます。', zh: '从主打文章进入分类、相关文章和站点地图路径。', es: 'Empieza por la nota principal y avanza por categorías, notas relacionadas y sitemap.', pt: 'Comece pela matéria principal e siga por categorias, artigos relacionados e sitemap.', de: 'Vom Hauptartikel führen klare Wege zu Kategorien, ähnlichen Artikeln und Sitemap.', fr: 'Commencez par l’article principal, puis passez aux catégories, articles liés et sitemap.', ar: 'ابدأ بالقصة الرئيسية ثم انتقل إلى التصنيفات والمقالات ذات الصلة وخريطة الموقع.', hi: 'मुख्य खबर से श्रेणियों, संबंधित लेखों और साइटमैप तक साफ रास्ता मिलता है।', id: 'Mulai dari berita utama, lalu lanjut ke kategori, artikel terkait, dan sitemap.' },
  readerWorkflow: { ko: '독자 탐색 흐름', en: 'Reader workflow', ja: '読者の流れ', zh: '阅读流程', es: 'Flujo de lectura', pt: 'Fluxo de leitura', de: 'Lesefluss', fr: 'Parcours lecteur', ar: 'مسار القارئ', hi: 'पाठक प्रवाह', id: 'Alur pembaca' },
  readerWorkflowHeading: { ko: '탐색-비교-확인 흐름', en: 'Find, compare, and verify quickly', ja: '探す・比べる・確認する', zh: '快速查找、比较和验证', es: 'Encuentra, compara y verifica rápido', pt: 'Encontre, compare e verifique rápido', de: 'Schnell finden, vergleichen und prüfen', fr: 'Trouver, comparer et vérifier vite', ar: 'ابحث وقارن وتحقق بسرعة', hi: 'जल्दी खोजें, तुलना करें और जांचें', id: 'Temukan, bandingkan, dan cek cepat' },
  readerWorkflowBody: { ko: '최신 기사에서 카테고리 허브, 관련 기사, 사이트맵까지 한 번에 이동할 수 있게 구성했습니다.', en: 'Move from latest stories to category hubs, related posts, and sitemap paths without leaving the site.', ja: '最新記事からカテゴリ、関連記事、サイトマップへサイト内で移動できます。', zh: '可从最新文章进入分类页、相关文章和站点地图。', es: 'Pasa de últimas noticias a categorías, artículos relacionados y sitemap sin salir del sitio.', pt: 'Vá das notícias recentes para categorias, posts relacionados e sitemap sem sair do site.', de: 'Wechseln Sie von aktuellen Artikeln zu Kategorien, ähnlichen Beiträgen und Sitemap.', fr: 'Passez des derniers articles aux catégories, articles liés et sitemap sans quitter le site.', ar: 'انتقل من الأخبار الحديثة إلى التصنيفات والمقالات ذات الصلة وخريطة الموقع داخل الموقع.', hi: 'नई खबरों से श्रेणी पेज, संबंधित पोस्ट और साइटमैप तक आसानी से जाएं।', id: 'Pindah dari berita terbaru ke kategori, artikel terkait, dan sitemap di dalam situs.' },
  categoryIntro: { ko: '이 섹션을 위해 선별한 기사입니다. 직접 일치하는 피드가 없을 때도 검증된 최신 기사를 보여줍니다.', en: 'Curated stories for this section. When a direct category match is unavailable, verified recent articles keep the page useful.', ja: 'このセクション向けに選んだ記事です。直接一致する配信がない場合も、検証済みの最新記事を表示します。', zh: '本栏目精选文章。没有直接匹配的来源时，也会展示已验证的最新文章。', es: 'Historias seleccionadas para esta sección. Si no hay una coincidencia directa, se muestran artículos recientes verificados.', pt: 'Histórias selecionadas para esta seção. Sem correspondência direta, exibimos artigos recentes verificados.', de: 'Ausgewählte Beiträge für diesen Bereich. Fehlt ein direkter Kategorien-Treffer, werden geprüfte aktuelle Artikel gezeigt.', fr: 'Articles sélectionnés pour cette rubrique. Sans correspondance directe, des articles récents vérifiés restent affichés.', ar: 'قصص مختارة لهذا القسم. عند غياب تطابق مباشر، تظهر مقالات حديثة تم التحقق منها.', hi: 'इस सेक्शन के लिए चुनी गई खबरें। सीधा मेल न होने पर भी सत्यापित ताज़ा लेख दिखाए जाते हैं।', id: 'Cerita pilihan untuk bagian ini. Jika tidak ada kecocokan langsung, artikel terbaru terverifikasi tetap ditampilkan.' },
  editorialTeam: { ko: '편집부', en: 'Editorial team', ja: '編集部', zh: '编辑部', es: 'Redacción', pt: 'Redação', de: 'Redaktion', fr: 'Rédaction', ar: 'فريق التحرير', hi: 'संपादकीय टीम', id: 'Tim redaksi' },
  advertisement: { ko: '광고', en: 'Advertisement', ja: '広告', zh: '广告', es: 'Publicidad', pt: 'Publicidade', de: 'Werbung', fr: 'Publicité', ar: 'إعلان', hi: 'विज्ञापन', id: 'Iklan' },
  keyPoints: { ko: '핵심 포인트', en: 'Key points', ja: '要点', zh: '要点', es: 'Puntos clave', pt: 'Pontos-chave', de: 'Kernpunkte', fr: 'Points clés', ar: 'نقاط رئيسية', hi: 'मुख्य बातें', id: 'Poin utama' },
  keyPointContext: { ko: '본문과 FAQ에서 맥락을 확인한 뒤 판단하세요.', en: 'Use the body and FAQ context before acting on this update.', ja: '本文とFAQの文脈を確認してから判断してください。', zh: '请先结合正文和FAQ背景再作判断。', es: 'Revisa el cuerpo y las FAQ antes de actuar sobre esta actualización.', pt: 'Use o texto e as perguntas frequentes antes de agir.', de: 'Nutzen Sie Text und FAQ-Kontext, bevor Sie handeln.', fr: 'Consultez le texte et la FAQ avant d’agir.', ar: 'راجع المتن والأسئلة الشائعة قبل اتخاذ قرار.', hi: 'इस अपडेट पर कदम उठाने से पहले लेख और FAQ का संदर्भ देखें।', id: 'Gunakan isi artikel dan FAQ sebelum bertindak.' },
  keyPointCompare: { ko: '카테고리 허브에서 유사 이슈를 함께 비교하세요.', en: 'Compare with related issues inside the category hub.', ja: 'カテゴリハブで関連トピックと比較してください。', zh: '可在分类页比较相关议题。', es: 'Compara temas relacionados dentro de la categoría.', pt: 'Compare temas relacionados dentro da categoria.', de: 'Vergleichen Sie verwandte Themen im Kategorie-Hub.', fr: 'Comparez avec des sujets liés dans la catégorie.', ar: 'قارن مع قضايا ذات صلة داخل قسم التصنيف.', hi: 'श्रेणी पेज में संबंधित मुद्दों से तुलना करें।', id: 'Bandingkan dengan isu terkait di kategori.' },
  categoryHub: { ko: '카테고리 허브', en: 'Category hub', ja: 'カテゴリハブ', zh: '分类页', es: 'Categoría', pt: 'Categoria', de: 'Kategorie-Hub', fr: 'Catégorie', ar: 'قسم التصنيف', hi: 'श्रेणी हब', id: 'Pusat kategori' },
  latestStories: { ko: '최신 기사', en: 'Latest stories', ja: '最新記事', zh: '最新文章', es: 'Últimas historias', pt: 'Últimas histórias', de: 'Neueste Beiträge', fr: 'Derniers articles', ar: 'أحدث القصص', hi: 'ताजा लेख', id: 'Berita terbaru' },
  nextReadingPath: { ko: '다음 읽기 경로', en: 'Next reading path', ja: '次の読書ルート', zh: '下一步阅读路径', es: 'Siguiente ruta de lectura', pt: 'Próxima rota de leitura', de: 'Nächster Lesepfad', fr: 'Prochain parcours', ar: 'مسار القراءة التالي', hi: 'अगला पढ़ने का रास्ता', id: 'Jalur baca berikutnya' },
  continueResearch: { ko: '다음 탐색 경로', en: 'Continue your research path', ja: '調査を続ける', zh: '继续研究路径', es: 'Continúa tu investigación', pt: 'Continue sua pesquisa', de: 'Recherche fortsetzen', fr: 'Poursuivre la recherche', ar: 'تابع مسار البحث', hi: 'अपना शोध आगे बढ़ाएं', id: 'Lanjutkan riset' },
  nextReadingBody: { ko: '관련 기사와 카테고리 허브를 함께 열어 같은 이슈를 여러 관점에서 비교하세요.', en: 'Open related articles and the category hub to compare this issue from several angles.', ja: '関連記事とカテゴリハブで複数の視点から比較できます。', zh: '打开相关文章和分类页，从多个角度比较该议题。', es: 'Abre artículos relacionados y la categoría para comparar el tema desde varios ángulos.', pt: 'Abra artigos relacionados e a categoria para comparar o tema por vários ângulos.', de: 'Öffnen Sie ähnliche Artikel und die Kategorie, um mehrere Blickwinkel zu vergleichen.', fr: 'Ouvrez les articles liés et la catégorie pour comparer plusieurs angles.', ar: 'افتح المقالات ذات الصلة وقسم التصنيف لمقارنة القضية من زوايا متعددة.', hi: 'कई दृष्टिकोणों से तुलना करने के लिए संबंधित लेख और श्रेणी पेज खोलें।', id: 'Buka artikel terkait dan kategori untuk membandingkan dari beberapa sudut.' },
  exploreCategory: { ko: '같은 카테고리 보기', en: 'Explore this category', ja: 'このカテゴリを見る', zh: '查看此分类', es: 'Explorar esta categoría', pt: 'Explorar esta categoria', de: 'Diese Kategorie ansehen', fr: 'Explorer cette catégorie', ar: 'استكشف هذا التصنيف', hi: 'यह श्रेणी देखें', id: 'Jelajahi kategori ini' },
  minuteShort: { ko: '분', en: 'm', ja: '分', zh: '分钟', es: 'min', pt: 'min', de: 'Min.', fr: 'min', ar: 'د', hi: 'मिनट', id: 'mnt' },
  llmsLatestArticles: { ko: '최신 기사', en: 'Latest Articles', ja: '最新記事', zh: '最新文章', es: 'Últimos artículos', pt: 'Últimos artigos', de: 'Neueste Artikel', fr: 'Derniers articles', ar: 'أحدث المقالات', hi: 'ताजा लेख', id: 'Artikel terbaru' }
};

export function getChannelLocale(locale: Locale): ChannelCopy {
  const byChannel = CHANNEL_COPIES[(channel as any).id] || CHANNEL_COPIES.MACRO;
  return byChannel[locale] || byChannel.ko;
}

export function channelLabel(key: keyof typeof LABELS, locale: Locale): string {
  return LABELS[key]?.[locale] || LABELS[key]?.en || key;
}

export function channelEditorial(locale: Locale): string {
  const copy = getChannelLocale(locale);
  const team = channelLabel('editorialTeam', locale);
  return locale === 'ko' ? `${copy.name} ${team}` : `${copy.name} ${team}`;
}
